### PR TITLE
change get to post

### PR DESCRIPTION
**Pull request by karkum**
@chivagarg @aswath87

### CODE REVIEW

**Comment by karkum** [comment]
I think these are the only places to update, let me know if I missed anything

**Comment by aswath87** [comment]
Looks good to me! @chivagarg knows this better

**Comment by chivagarg** [comment]
Sorry for the late response, india is taking a toll on me :D

i think that all calls to  createNuggets should be PUT calls (others can be
get):

https://github.com/nuggets-rocks/nuggets_chrome_extension_v2/blob/master/nuggets-chrome-extension/js/globals.js
and
https://github.com/nuggets-rocks/nuggets_chrome_extension_v2/blob/master/nuggets-chrome-extension/js/contextmenu.js

**Comment by karkum** [comment]
@chivagarg see #2

**Pull request merged**
